# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'first_use.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_firstUse(object):
    def setupUi(self, firstUse):
        firstUse.setObjectName("firstUse")
        firstUse.resize(289, 223)
        self.verticalLayout = QtWidgets.QVBoxLayout(firstUse)
        self.verticalLayout.setObjectName("verticalLayout")
        self.SubtitleLabel = SubtitleLabel(firstUse)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.verticalLayout.addWidget(self.SubtitleLabel)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.BodyLabel = BodyLabel(firstUse)
        self.BodyLabel.setObjectName("BodyLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.BodyLabel)
        self.gamePathEdit = LineEdit(firstUse)
        self.gamePathEdit.setProperty("transparent", False)
        self.gamePathEdit.setProperty(
            "lightCustomQss", 'LineEdit[type="error"] {\n' "    color: red;\n" "}"
        )
        self.gamePathEdit.setProperty(
            "darkCustomQss", 'LineEdit[type="error"] {\n' "    color: red;\n" "}"
        )
        self.gamePathEdit.setObjectName("gamePathEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.gamePathEdit)
        self.BodyLabel_2 = BodyLabel(firstUse)
        self.BodyLabel_2.setObjectName("BodyLabel_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.BodyLabel_2)
        self.disablePathEdit = LineEdit(firstUse)
        self.disablePathEdit.setObjectName("disablePathEdit")
        self.formLayout.setWidget(
            1, QtWidgets.QFormLayout.FieldRole, self.disablePathEdit
        )
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(
            40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum
        )
        self.horizontalLayout.addItem(spacerItem)
        self.sureBtn = PrimaryPushButton(firstUse)
        self.sureBtn.setEnabled(False)
        self.sureBtn.setObjectName("sureBtn")
        self.horizontalLayout.addWidget(self.sureBtn)
        self.quitBtn = PushButton(firstUse)
        self.quitBtn.setObjectName("quitBtn")
        self.horizontalLayout.addWidget(self.quitBtn)
        self.horizontalLayout.setStretch(0, 6)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(2, 2)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(firstUse)
        self.gamePathEdit.textChanged["QString"].connect(firstUse.verify)  # type: ignore
        self.disablePathEdit.textChanged["QString"].connect(firstUse.verify)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(firstUse)

    def retranslateUi(self, firstUse):
        _translate = QtCore.QCoreApplication.translate
        firstUse.setWindowTitle(_translate("firstUse", "首次配置"))
        self.SubtitleLabel.setText(_translate("firstUse", "设置配置路径"))
        self.BodyLabel.setText(_translate("firstUse", "游戏文件夹"))
        self.gamePathEdit.setPlaceholderText(_translate("firstUse", "游戏根目录"))
        self.BodyLabel_2.setText(_translate("firstUse", "禁用mod文件夹"))
        self.disablePathEdit.setPlaceholderText(
            _translate("firstUse", "禁用mod路径(不存在会自动创建文件)")
        )
        self.sureBtn.setText(_translate("firstUse", "确定"))
        self.quitBtn.setText(_translate("firstUse", "退出"))


from qfluentwidgets import (
    BodyLabel,
    LineEdit,
    PrimaryPushButton,
    PushButton,
    SubtitleLabel,
)
