# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_modShowView(object):
    def setupUi(self, modShowView):
        modShowView.setObjectName("modShowView")
        modShowView.resize(882, 876)
        modShowView.setTabletTracking(False)
        self.verticalLayout = QtWidgets.QVBoxLayout(modShowView)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.search_edit = SearchLineEdit(modShowView)
        self.search_edit.setObjectName("search_edit")
        self.horizontalLayout.addWidget(self.search_edit)
        self.refresh_btn = PushButton(modShowView)
        self.refresh_btn.setToolTip("")
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        self.menu_btn = DropDownPushButton(modShowView)
        self.menu_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.menu_btn.setObjectName("menu_btn")
        self.horizontalLayout.addWidget(self.menu_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.splitter = QtWidgets.QSplitter(modShowView)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setHandleWidth(6)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.tableView = ModShowTableView(self.splitter)
        self.tableView.setObjectName("tableView")
        self.vkp_info = QtWidgets.QWidget(self.splitter)
        self.vkp_info.setObjectName("vkp_info")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.vkp_info)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(286, 37, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem2)
        self.file_pic = PixmapLabel(self.vkp_info)
        self.file_pic.setObjectName("file_pic")
        self.verticalLayout_2.addWidget(self.file_pic)
        self.addons_info = PlainTextEdit(self.vkp_info)
        self.addons_info.setTabletTracking(False)
        self.addons_info.setTabChangesFocus(True)
        self.addons_info.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.addons_info.setReadOnly(True)
        self.addons_info.setBackgroundVisible(False)
        self.addons_info.setObjectName("addons_info")
        self.verticalLayout_2.addWidget(self.addons_info)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem3)
        self.verticalLayout_2.setStretch(2, 5)
        self.verticalLayout.addWidget(self.splitter)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)

        self.retranslateUi(modShowView)
        self.search_edit.searchSignal['QString'].connect(modShowView.perform_search) # type: ignore
        self.search_edit.textChanged['QString'].connect(modShowView.perform_search) # type: ignore
        self.search_edit.clearSignal.connect(modShowView.perform_search) # type: ignore
        self.splitter.splitterMoved['int','int'].connect(modShowView.on_splitter_moved) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(modShowView)
        modShowView.setTabOrder(self.search_edit, self.refresh_btn)
        modShowView.setTabOrder(self.refresh_btn, self.tableView)

    def retranslateUi(self, modShowView):
        _translate = QtCore.QCoreApplication.translate
        modShowView.setWindowTitle(_translate("modShowView", "Frame"))
        self.refresh_btn.setText(_translate("modShowView", "刷新"))
        self.refresh_btn.setShortcut(_translate("modShowView", "F5"))
        self.menu_btn.setText(_translate("modShowView", "全部"))
from qfluentwidgets import DropDownPushButton, PixmapLabel, PlainTextEdit, PushButton, SearchLineEdit
from views.components.mod_show_tableview import ModShowTableView
