# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'update_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_updateView(object):
    def setupUi(self, updateView):
        updateView.setObjectName("updateView")
        updateView.resize(629, 560)
        self.verticalLayout = QtWidgets.QVBoxLayout(updateView)
        self.verticalLayout.setContentsMargins(20, 20, 20, 20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.update_info = TextBrowser(updateView)
        self.update_info.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.update_info.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.update_info.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.update_info.setObjectName("update_info")
        self.verticalLayout.addWidget(self.update_info)

        self.retranslateUi(updateView)
        QtCore.QMetaObject.connectSlotsByName(updateView)

    def retranslateUi(self, updateView):
        _translate = QtCore.QCoreApplication.translate
        updateView.setWindowTitle(_translate("updateView", "Form"))
from qfluentwidgets import TextBrowser
