"""init

Revision ID: bbe0c98ff88c
Revises:
Create Date: 2025-12-21 03:08:48.933994

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bbe0c98ff88c"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "classification",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True, comment="类型名称"),
        sa.Column("type", sa.String(), nullable=True, comment="mod分类,默认为全部"),
        sa.PrimaryKeyConstraint("id"),
        comment="切换整套mod名称信息",
    )
    op.create_table(
        "vpkInfo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("fileName", sa.String(), nullable=True, comment="VPK文件名称"),
        sa.Column("category", sa.String(), nullable=True, comment="一级分类"),
        sa.Column("subCategory", sa.String(), nullable=True, comment="二级分类"),
        sa.Column("customTitle", sa.String(), nullable=True, comment="mod自定义名称"),
        sa.Column(
            "addonInfo", sa.JSON(), nullable=True, comment="原始addonInfo文件解析内容"
        ),
        sa.Column(
            "addonInfoContent", sa.String(), nullable=True, comment="addonInfo原始内容"
        ),
        sa.Column(
            "customAddonInfo",
            sa.JSON(),
            nullable=True,
            comment="addonInfo解析,修改内容",
        ),
        sa.Column(
            "customAddonInfoContent",
            sa.String(),
            nullable=True,
            comment="addonInfo修改后的内容",
        ),
        sa.Column("url", sa.String(), nullable=True, comment="mod获取链接"),
        sa.Column("modComment", sa.String(), nullable=True, comment="mod信息备注"),
        sa.PrimaryKeyConstraint("id"),
        comment="vpk信息",
    )
    op.create_index(op.f("ix_vpkInfo_category"), "vpkInfo", ["category"], unique=False)
    op.create_index(op.f("ix_vpkInfo_fileName"), "vpkInfo", ["fileName"], unique=True)
    op.create_index(
        op.f("ix_vpkInfo_subCategory"), "vpkInfo", ["subCategory"], unique=False
    )
    op.create_table(
        "classificationInfo",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "typeId", sa.Integer(), nullable=True, comment="外键,对应Classification的id"
        ),
        sa.Column("vpkInfoId", sa.Integer(), nullable=True),
        sa.Column("serialNumber", sa.Integer(), nullable=False, comment="排序"),
        sa.Column("enable", sa.Integer(), nullable=False, comment="是否启用"),
        sa.CheckConstraint("enable IN (0, 1)", name="check_enable_value"),
        sa.ForeignKeyConstraint(
            ["typeId"],
            ["classification.id"],
        ),
        sa.ForeignKeyConstraint(
            ["vpkInfoId"],
            ["vpkInfo.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        comment="切换mod组信息",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("classificationInfo")
    op.drop_index(op.f("ix_vpkInfo_subCategory"), table_name="vpkInfo")
    op.drop_index(op.f("ix_vpkInfo_fileName"), table_name="vpkInfo")
    op.drop_index(op.f("ix_vpkInfo_category"), table_name="vpkInfo")
    op.drop_table("vpkInfo")
    op.drop_table("classification")
    # ### end Alembic commands ###
