# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'edit_type_info_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import pyqtSignal
from PyQt5.QtGui import QDropEvent, QDragEnterEvent


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 1000)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.saveNameEdit = LineEdit(Form)
        self.saveNameEdit.setMaximumSize(QtCore.QSize(300, 33))
        self.saveNameEdit.setInputMask("")
        self.saveNameEdit.setText("")
        self.saveNameEdit.setObjectName("saveNameEdit")
        self.horizontalLayout.addWidget(self.saveNameEdit)
        self.typeBox = DropDownPushButton(Form)
        self.typeBox.setMaximumSize(QtCore.QSize(150, 16777215))
        self.typeBox.setObjectName("typeBox")
        self.horizontalLayout.addWidget(self.typeBox)
        self.syncType = CheckBox(Form)
        self.syncType.setObjectName("syncType")
        self.horizontalLayout.addWidget(self.syncType)
        self.searchLineEdit = SearchLineEdit(Form)
        self.searchLineEdit.setMaximumSize(QtCore.QSize(400, 33))
        self.searchLineEdit.setObjectName("searchLineEdit")
        self.horizontalLayout.addWidget(self.searchLineEdit)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 2)
        self.horizontalLayout.setStretch(3, 4)
        self.horizontalLayout.setStretch(4, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.page_2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem1 = QtWidgets.QSpacerItem(396, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.ProgressBar = ProgressBar(self.page_2)
        self.ProgressBar.setMaximumSize(QtCore.QSize(16777215, 10))
        self.ProgressBar.setOrientation(QtCore.Qt.Horizontal)
        self.ProgressBar.setObjectName("ProgressBar")
        self.horizontalLayout_5.addWidget(self.ProgressBar)
        self.horizontalLayout_5.setStretch(0, 6)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.SubtitleLabel = SubtitleLabel(self.page_2)
        self.SubtitleLabel.setObjectName("SubtitleLabel")
        self.horizontalLayout_6.addWidget(self.SubtitleLabel)
        self.loadingModText = SubtitleLabel(self.page_2)
        self.loadingModText.setObjectName("loadingModText")
        self.horizontalLayout_6.addWidget(self.loadingModText)
        self.horizontalLayout_6.setStretch(0, 2)
        self.horizontalLayout_6.setStretch(1, 7)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_7.addLayout(self.verticalLayout_3)
        spacerItem4 = QtWidgets.QSpacerItem(396, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem4)
        self.horizontalLayout_7.setStretch(0, 3)
        self.horizontalLayout_7.setStretch(1, 4)
        self.horizontalLayout_7.setStretch(2, 3)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.disabledWdiget = ListWidget(self.page_3)
        self.disabledWdiget.setMinimumSize(QtCore.QSize(50, 0))
        self.disabledWdiget.setToolTip("")
        self.disabledWdiget.setStatusTip("")
        self.disabledWdiget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.disabledWdiget.setObjectName("disabledWdiget")
        self.horizontalLayout_4.addWidget(self.disabledWdiget)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.enabledBtn = PushButton(self.page_3)
        self.enabledBtn.setEnabled(False)
        self.enabledBtn.setObjectName("enabledBtn")
        self.verticalLayout.addWidget(self.enabledBtn)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.disabledBtn = PushButton(self.page_3)
        self.disabledBtn.setEnabled(False)
        self.disabledBtn.setObjectName("disabledBtn")
        self.verticalLayout.addWidget(self.disabledBtn)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem7)
        self.disableAllBtn = PushButton(self.page_3)
        self.disableAllBtn.setEnabled(False)
        self.disableAllBtn.setObjectName("disableAllBtn")
        self.verticalLayout.addWidget(self.disableAllBtn)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem8)
        self.verticalLayout.setStretch(0, 3)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(3, 1)
        self.verticalLayout.setStretch(5, 1)
        self.verticalLayout.setStretch(6, 3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.enabledWidget = CListWidget(self.page_3)
        self.enabledWidget.setEnabled(True)
        self.enabledWidget.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.enabledWidget.setObjectName("enabledWidget")
        self.horizontalLayout_4.addWidget(self.enabledWidget)
        self.stackedWidget.addWidget(self.page_3)
        self.horizontalLayout_3.addWidget(self.stackedWidget)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.saveBtn = PrimaryPushButton(Form)
        self.saveBtn.setEnabled(False)
        self.saveBtn.setObjectName("saveBtn")
        self.horizontalLayout_2.addWidget(self.saveBtn)
        self.closeBtn = PushButton(Form)
        self.closeBtn.setObjectName("closeBtn")
        self.horizontalLayout_2.addWidget(self.closeBtn)
        self.horizontalLayout_2.setStretch(0, 8)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(1)
        self.searchLineEdit.textChanged['QString'].connect(Form.searchChange) # type: ignore
        self.searchLineEdit.clearSignal.connect(Form.searchChange) # type: ignore
        self.searchLineEdit.searchSignal['QString'].connect(Form.searchChange) # type: ignore
        self.enabledBtn.clicked.connect(Form.enableMod) # type: ignore
        self.disableAllBtn.clicked.connect(Form.disableAllMod) # type: ignore
        self.disabledBtn.clicked.connect(Form.disableMod) # type: ignore
        self.disabledWdiget.doubleClicked['QModelIndex'].connect(Form.copyFileTitle) # type: ignore
        self.enabledWidget.doubleClicked['QModelIndex'].connect(Form.copyFileTitle) # type: ignore
        self.saveBtn.clicked.connect(Form.savePage) # type: ignore
        self.closeBtn.clicked.connect(Form.close) # type: ignore
        self.saveNameEdit.textChanged['QString'].connect(Form.fileNameChanged) # type: ignore
        self.syncType.toggled['bool'].connect(Form.syncTypeBtnChanged) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.saveNameEdit.setPlaceholderText(_translate("Form", "保存名称"))
        self.typeBox.setText(_translate("Form", "全部"))
        self.syncType.setText(_translate("Form", "分类筛选两侧"))
        self.searchLineEdit.setPlaceholderText(_translate("Form", "搜索"))
        self.SubtitleLabel.setText(_translate("Form", "正在加载:"))
        self.loadingModText.setText(_translate("Form", "加载中..."))
        self.enabledBtn.setText(_translate("Form", "启用"))
        self.disabledBtn.setText(_translate("Form", "禁用"))
        self.disableAllBtn.setText(_translate("Form", "全部禁用"))
        self.saveBtn.setText(_translate("Form", "保存"))
        self.closeBtn.setText(_translate("Form", "关闭"))
from qfluentwidgets import CheckBox, DropDownPushButton, LineEdit, ListWidget, PrimaryPushButton, ProgressBar, PushButton, SearchLineEdit, SubtitleLabel


class CListWidget(ListWidget):
    dropChanged = pyqtSignal()

    def dragMoveEvent(self, event):
        # 获取当前拖拽项的行号
        current_row = self.currentRow()
        # 获取目标位置的行号（若无效则返回-1）
        target_row = self.indexAt(event.pos()).row()
        # 忽略无效拖拽位置（如底部边界）
        if (target_row == current_row + 1) or (current_row == self.count() - 1 and target_row == -1):
            event.ignore()
        else:
            super().dragMoveEvent(event)
    def dropEvent(self, e: QDropEvent):
        old_order = [self.item(i).text() for i in range(self.count())]
        super().dropEvent(e)  # 先执行默认行为
        new_order = [self.item(i).text() for i in range(self.count())]

        if old_order != new_order:
            print("实际顺序已改变")
            self.dropChanged.emit()
        else:
            print("无效拖拽，未改变顺序")

