# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mod_switch.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ModSwitchInterface(object):
    def setupUi(self, ModSwitchInterface):
        ModSwitchInterface.setObjectName("ModSwitchInterface")
        ModSwitchInterface.resize(944, 624)
        self.horizontalLayout = QtWidgets.QHBoxLayout(ModSwitchInterface)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.switch_type_info = ListWidget(ModSwitchInterface)
        self.switch_type_info.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.switch_type_info.setObjectName("switch_type_info")
        self.horizontalLayout.addWidget(self.switch_type_info)
        self.switch_type_show = ListWidget(ModSwitchInterface)
        self.switch_type_show.setContextMenuPolicy(QtCore.Qt.NoContextMenu)
        self.switch_type_show.setObjectName("switch_type_show")
        self.horizontalLayout.addWidget(self.switch_type_show)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)

        self.retranslateUi(ModSwitchInterface)
        QtCore.QMetaObject.connectSlotsByName(ModSwitchInterface)

    def retranslateUi(self, ModSwitchInterface):
        _translate = QtCore.QCoreApplication.translate
        ModSwitchInterface.setWindowTitle(_translate("ModSwitchInterface", "Form"))
from qfluentwidgets import ListWidget
