# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'modules_page.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(733, 510)
        self.gridLayout = QtWidgets.QGridLayout(Frame)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.search_edit = SearchLineEdit(Frame)
        self.search_edit.setObjectName("search_edit")
        self.horizontalLayout.addWidget(self.search_edit)
        self.refresh_btn = PushButton(Frame)
        self.refresh_btn.setToolTip("")
        self.refresh_btn.setObjectName("refresh_btn")
        self.horizontalLayout.addWidget(self.refresh_btn)
        self.type_btn = ComboBox(Frame)
        self.type_btn.setMinimumSize(QtCore.QSize(120, 0))
        self.type_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.type_btn.setStyleSheet("ComboBox {\n"
"    border: 1px solid rgba(0, 0, 0, 0.073);\n"
"    border-radius: 5px;\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.183);\n"
"    padding: 5px 31px 6px 11px;\n"
"    /* font: 14px \'Segoe UI\', \'Microsoft YaHei\', \'PingFang SC\'; */\n"
"    color: black;\n"
"    background-color: rgba(255, 255, 255, 0.7);\n"
"    text-align: center;\n"
"    outline: none;\n"
"}\n"
"\n"
"ComboBox:hover {\n"
"    background-color: rgba(249, 249, 249, 0.5);\n"
"}\n"
"\n"
"ComboBox:pressed {\n"
"    background-color: rgba(249, 249, 249, 0.3);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.073);\n"
"    color: rgba(0, 0, 0, 0.63);\n"
"}\n"
"\n"
"ComboBox:disabled {\n"
"    color: rgba(0, 0, 0, 0.36);\n"
"    background: rgba(249, 249, 249, 0.3);\n"
"    border: 1px solid rgba(0, 0, 0, 0.06);\n"
"    border-bottom: 1px solid rgba(0, 0, 0, 0.06);\n"
"}\n"
"\n"
"ComboBox[isPlaceholderText=true] {\n"
"    color: rgba(0, 0, 0, 0.6063);\n"
"}")
        self.type_btn.setObjectName("type_btn")
        self.horizontalLayout.addWidget(self.type_btn)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 2)
        self.vkp_info = QtWidgets.QVBoxLayout()
        self.vkp_info.setObjectName("vkp_info")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vkp_info.addItem(spacerItem2)
        self.file_pic = PixmapLabel(Frame)
        self.file_pic.setObjectName("file_pic")
        self.vkp_info.addWidget(self.file_pic)
        self.addons_info = PlainTextEdit(Frame)
        self.addons_info.setLineWrapMode(QtWidgets.QPlainTextEdit.NoWrap)
        self.addons_info.setReadOnly(True)
        self.addons_info.setBackgroundVisible(False)
        self.addons_info.setObjectName("addons_info")
        self.vkp_info.addWidget(self.addons_info)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.vkp_info.addItem(spacerItem3)
        self.vkp_info.setStretch(2, 5)
        self.gridLayout.addLayout(self.vkp_info, 1, 1, 1, 1)
        self.tableView = CustomTableView(Frame)
        self.tableView.setObjectName("tableView")
        self.gridLayout.addWidget(self.tableView, 1, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 7)

        self.retranslateUi(Frame)
        self.search_edit.searchSignal['QString'].connect(Frame.perform_search) # type: ignore
        self.search_edit.textChanged['QString'].connect(Frame.perform_search) # type: ignore
        self.search_edit.clearSignal.connect(Frame.perform_search) # type: ignore
        self.type_btn.clicked.connect(Frame.show_type_menu) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.refresh_btn.setText(_translate("Frame", "刷新"))
        self.type_btn.setText(_translate("Frame", "全部"))
from common.widget.custom_table_widget import CustomTableView
from qfluentwidgets import ComboBox, PixmapLabel, PlainTextEdit, PushButton, SearchLineEdit
